version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: fauves
      POSTGRES_PASSWORD: fauves
      POSTGRES_DB: fauves
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://fauves:fauves@db:5432/fauves?schema=public
      JWT_SECRET: changeme-in-prod
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      # Opcional: VITE_API_BASE se quiser forçar
      VITE_API_BASE: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
