name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        run: npm install --legacy-peer-deps
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build
      - name: Test
        run: npm test --if-present

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build

  docker-images:
    needs: [backend-test, frontend-build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        if: secrets.GITHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fauves-backend:latest backend
      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fauves-frontend:latest frontend
      - name: Push images
        if: secrets.GITHUB_TOKEN != ''
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/fauves-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/fauves-frontend:latest
